version: '3.8'

services:
  compiler-backend-interactive:
    build:
      context: .
      dockerfile: Dockerfile
    image: compiler-backend:latest
    container_name: compiler-backend-interactive
    volumes:
      - .:/app
    command: bash
    stdin_open: true
    tty: true

  compiler-backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: compiler-backend:latest
    container_name: compiler-backend-api
    volumes:
      - .:/app
    command: python src/api.py
    ports:
      - "5000:5000"
