version: '3.8'

services:
  compiler-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: compiler-backend:latest
    container_name: compiler-backend
    volumes:
      - .:/app
    command: bash
    stdin_open: true
    tty: true
